name: C/C++ CI

on:
  pull_request:
    branches: [ "*" ]

jobs:

  ubsan-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: run-tests
      run: python3 ./run_test.py ubsan

  asan-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: run-tests
      run: python3 ./run_test.py asan

  tsan-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: run-tests
      run: python3 ./run_test.py tsan
